// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZRdyT2OGpPQpdqsew2u9EHYztwOj7l50',
    appId: '1:938315548562:web:a05fc8c55b09625599634b',
    messagingSenderId: '938315548562',
    projectId: 'mining-2d954',
    authDomain: 'mining-2d954.firebaseapp.com',
    storageBucket: 'mining-2d954.appspot.com',
    measurementId: 'G-T27DKSP989',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASzOf06rNyC1kDLnlizBUQ58DbAPoN7tQ',
    appId: '1:938315548562:android:0633a554a3dc08b599634b',
    messagingSenderId: '938315548562',
    projectId: 'mining-2d954',
    storageBucket: 'mining-2d954.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgDmzFQQUzTS3UA33VPnKSB0TTsmhjQG4',
    appId: '1:938315548562:ios:739391c0fa4e627999634b',
    messagingSenderId: '938315548562',
    projectId: 'mining-2d954',
    storageBucket: 'mining-2d954.appspot.com',
    iosBundleId: 'com.example.mining',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgDmzFQQUzTS3UA33VPnKSB0TTsmhjQG4',
    appId: '1:938315548562:ios:739391c0fa4e627999634b',
    messagingSenderId: '938315548562',
    projectId: 'mining-2d954',
    storageBucket: 'mining-2d954.appspot.com',
    iosBundleId: 'com.example.mining',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZRdyT2OGpPQpdqsew2u9EHYztwOj7l50',
    appId: '1:938315548562:web:65eb32ec14a76a8a99634b',
    messagingSenderId: '938315548562',
    projectId: 'mining-2d954',
    authDomain: 'mining-2d954.firebaseapp.com',
    storageBucket: 'mining-2d954.appspot.com',
    measurementId: 'G-P34Z93QW3C',
  );
}
